config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Admin
  get "/admin", to: "admin/home#index"
  namespace :admin do
    resources :enterprises, except: %i[index destroy]
  end

  # Campaigns
  namespace :campaigns do
    get "marketer/show"
    # Invitations
    resources :invitations, param: :token, except: %i[index destroy]
    # Sessions
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    # Registration
    get "/account", to: "marketers#edit"
    patch "/account", to: "marketers#update"
    # Password
    resources :passwords, param: :token, except: %i[index show]

    # Enterprises
    resources :merchants, except: :destroy do
    end
    put "merchants/:id/location", to: "merchants#location", as: "merchant_location"

    get "/account", to: "marketers#edit"
    patch "/account", to: "marketers#update"
  end

  # Registration
  get "/account", to: "admins#edit"
  patch "/account", to: "admins#update"
  resources :user_invitations, only: %i[new create edit update]

  # Session
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  # Enterprises
  get "/settings", to: "enterprises#edit", as: :enterprise_setting
  delete "remove_user/:user_id", to: "enterprises#remove_user", as: :remove_enterprise_user

  # Branches
  resources :branches, except: %i[index destroy]

  # Password
  resources :passwords, param: :token, except: %i[index show]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :deliveries do
    collection do
      get :search_customer
      get :search_branch
    end
  end
  put "deliveries/:id/confirm_arrival", to: "deliveries#confirm_arrival", as: :confirm_arrival
  put "deliveries/:id/confirm_delivery", to: "deliveries#confirm_delivery", as: :confirm_delivery

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "enterprises#index"
end

app/views/admins/edit.html.erb
<div class="flex w-full flex-col justify-center mt-6 w-full md:w-3/5 mx-auto px-2">
  <div class="flex sm:w-full justify-between items-center mb-6">
    <h2 class="text-center text-2xl/9 font-bold tracking-tight text-gray-900">
      <%= t('.title') %>
    </h2>
    <%= button_to t(".log_out"), logout_path, class: "btn btn-danger", method: :delete %>
  </div>

  <%= form_with model: current_user, url: account_path, class: "w-full" do |form| %>
    <div class="grid grid-cols-1 sm:grid-cols-2 gap-x-4">
      <div class="form-group">
        <%= form.label :enterprise, t(".enterprise"), class: "form-label" %>
        <%= form.text_field :enterprise_name, value: current_user.enterprise.name, disabled: true, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :branch, t(".branch"), class: "form-label" %>
        <%= form.text_field :branch, value: current_user.branch&.name, disabled: true, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :full_name, t(".full_name.label"), class: "form-label" %>
        <%= form.text_field :full_name, autofocus: true, placeholder: t(".full_name.placeholder"),
              class: "form-control #{'is-invalid' if current_user.errors.messages[:full_name].present?}" %>
        <% if current_user.errors.messages[:full_name].present? %>
          <div class="invalid-feedback">
            <% current_user.errors.messages[:full_name].each do |message| %>
              <span><%= message %></span>
            <% end %>
          </div>
        <% end %>
      </div>

      <div class="form-group">
        <%= form.label :telephone, t(".telephone.label"), class: "form-label" %>
        <%= form.text_field :telephone, autofocus: false, placeholder: t(".telephone.placeholder"),
              class: "form-control", disabled: true %>
      </div>
    </div>

    <%= form.submit t(".submit"), class: "btn btn-primary" %>
  <% end %>
</div>