config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Admin
  get "/admin", to: "admin/home#index"
  namespace :admin do
    resources :enterprises, except: %i[index destroy]
  end

  # Campaigns
  namespace :campaigns do
    get "marketer/show"
    # Invitations
    resources :invitations, param: :token, except: %i[index destroy]
    # Sessions
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    # Registration
    get "/account", to: "marketers#edit"
    patch "/account", to: "marketers#update"
    # Password
    resources :passwords, param: :token, except: %i[index show]

    # Enterprises
    resources :merchants, except: :destroy do
    end
    put "merchants/:id/location", to: "merchants#location", as: "merchant_location"

    get "/account", to: "marketers#edit"
    patch "/account", to: "marketers#update"
  end

  # Registration
  get "/account", to: "admins#edit"
  patch "/account", to: "admins#update"
  resources :user_invitations, only: %i[new create edit update]

  # Session
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  # Enterprises
  get "/settings", to: "enterprises#edit", as: :enterprise_setting
  delete "remove_user/:user_id", to: "enterprises#remove_user", as: :remove_enterprise_user

  # Branches
  resources :branches, except: %i[index destroy]

  # Password
  resources :passwords, param: :token, except: %i[index show]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :deliveries do
    collection do
      get :search_customer
      get :search_branch
    end
  end
  put "deliveries/:id/confirm_arrival", to: "deliveries#confirm_arrival", as: :confirm_arrival
  put "deliveries/:id/confirm_delivery", to: "deliveries#confirm_delivery", as: :confirm_delivery

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "enterprises#index"
end

app/controllers/campaigns/application_controller.rb
module Campaigns
  class ApplicationController < ActionController::Base
    include MarketerAuthentication
    before_action :require_admin
    before_action :set_current_user
    # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
    allow_browser versions: :modern
    helper_method :current_user

    layout "campaigns"

    private

    def require_admin
      http_basic_authenticate_or_request_with name: Rails.application.credentials["app_username"] || "",
                                  password: Rails.application.credentials["app_password"] || ""
    end

    def set_current_user
      @current_user ||= Current.marketer

      if @current_user && !@current_user.confirmed
        redirect_to campaigns_login_path, notice: t("campaigns.invitations.unconfirmed_message")
      end
    end

    def current_user
      @current_user
    end
  end
end

app/controllers/campaigns/invitations_controller.rb
module Campaigns
  class InvitationsController < ApplicationController
    allow_unauthenticated_access
    skip_before_action :require_admin, only: %i[edit update]
    before_action :set_marketer_by_token, only: %i[edit update]

    def new
      @marketer = Marketer.new
      respond_to do |format|
        format.json do
          render json: { html: render_to_string("campaigns/invitations/new",
                                                 layout: false, formats: :html) }
        end
      end
    end

    def create
      @marketer = Marketer.invite_new(params.require(:marketer).permit(:email))

      if @marketer.persisted? && @marketer.errors.none?
        flash[:success] = t("campaigns.invitations.sent", email: @marketer.escape_value(:email))
        redirect_back fallback_location: admin_path(params: { option: "marketers" })
      else
        render turbo_stream: turbo_stream.replace("new_marketer", partial: "campaigns/invitations/new_form",
                                                    locals: { marketer: @marketer }),
                status: :unprocessable_entity
      end
    end

    def edit; end

    def update
      if @marketer.update(
        params.require(:marketer)
              .permit(:password, :password_confirmation, :full_name).merge(confirmed: true)
      )
        start_new_session_for(@marketer)

        flash[:success] = t("campaigns.invitations.confirmed")
        redirect_to campaigns_merchants_path
      else
        render :edit, status: :unprocessable_entity
      end
    end

    private

    def set_marketer_by_token
      @marketer = Marketer.find_by_token_for!(:invitation, params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to campaigns_login_path, alert: t("campaigns.invitations.invalid_token")
    end
  end
end

app/controllers/campaigns/marketers_controller.rb
module Campaigns
  class MarketersController < ApplicationController
    skip_before_action :require_admin

    def edit
    end

    def update
      if current_user.update(params.require(:marketer).permit(:full_name))
        flash[:success] = t("flash.update_success", name: t("campaigns.marketers.account"))
        redirect_to campaigns_account_path
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end
end

app/controllers/campaigns/merchants_controller.rb
module Campaigns
  class MerchantsController < ApplicationController
    skip_before_action :require_admin
    before_action :set_merchant, only: %i[edit update location]

    def index
      @merchants = @current_user.merchants.order(:created_at)
    end

    def new
      @merchant = @current_user.merchants.new
      @manager = @merchant.managers.new
      authorize! :create_merchant, @merchant
    end

    def create
      @merchant = @current_user.merchants.new
      authorize! :create_merchant, @merchant

      @merchant, @manager = @current_user.create_merchant(merchant_params, manager_params)

      if @merchant.persisted?
        redirect_to edit_campaigns_merchant_path(@merchant)
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
      authorize! :create_merchant, @merchant
    end

    def update
      authorize! :create_merchant, @merchant

      if @merchant.update(merchant_params.except(:images))
        if merchant_params[:images].last.present?
          @merchant.update(images: merchant_params[:images])
        end

        flash[:success] = t("flash.update_success", name: @merchant.escape_value(:name))
        redirect_to edit_campaigns_merchant_path(@merchant)
      else
        render :edit, status: :upprocessable_entity
      end
    end

    def location
      if params[:latitude] && params[:longitude]
        @merchant.update(location: { latitude: params[:latitude], longitude: params[:longitude] })
        flash[:success] = t("flash.update_success", name: t("campaigns.merchants.location"))
        redirect_to edit_campaigns_merchant_path(@merchant)
      else
        flash[:error] = t("flash.update_fail", name: t("campaigns.merchants.location"))
        redirect_to edit_campaigns_merchant_path(@merchant)
      end
    end

    private

    def set_merchant
      @merchant = @current_user.merchants.find(params[:id])
    end

    def merchant_params
      params.require(:enterprise).permit(:name, :category, :description, :city, images: [])
    end

    def manager_params
      params.require(:manager).permit(:telephone)
    end
  end
end

app/controllers/campaigns/passwords_controller.rb
module Campaigns
  class PasswordsController < ApplicationController
    skip_before_action :require_admin
    allow_unauthenticated_access
    before_action :set_marketer_by_token, only: %i[ edit update ]
    before_action :verify_invitation_token, only: %i[ edit update ]

    def new; end

    def create
      if marketer = Marketer.find_by(email: params[:email])
        if !marketer.confirmed
          redirect_to campaigns_login_path, alert: t("campaigns.passwords.confirm_account")
          return
        end

        Campaigns::PasswordMailer.reset(marketer).deliver_later
        redirect_to campaigns_login_path, notice: t("campaigns.passwords.instruction_sent")
      else
        redirect_to campaigns_login_path, alert: t("campaigns.passwords.invalid_email")
      end
    end

    def edit; end

    def update
      if @marketer.update(password_params)
        redirect_to campaigns_login_path, notice: t("campaigns.passwords.reset_successful")
      else
        render :edit, status: :unprocessable_entity
      end
    end

    private

    def set_marketer_by_token
      @marketer = Marketer.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to campaigns_login_path, alert: t("campaigns.passwords.invalid_token")
    end

    def password_params
      params.permit(:password, :password_confirmation)
    end

    def verify_invitation_token
      if !@marketer.confirmed
        redirect_to campaigns_login_path, alert: t("campaigns.passwords.confirm_account")
      end
    end
  end
end

app/controllers/campaigns/sessions_controller.rb
module Campaigns
  class SessionsController < ApplicationController
    allow_unauthenticated_access only: %i[ new create ]
    skip_before_action :require_admin
    rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to root_path, alert: "Try again later." }

    def new; end

    def create
      if marketer = Marketer.authenticate_by(params.permit(:email, :password))
        start_new_session_for marketer
        redirect_to after_authentication_url
      else
        flash.now[:alert] = t("campaigns.sessions.invalid_credentials")
        render :new, status: :unprocessable_entity
      end
    end

    def destroy
      terminate_session
      redirect_to campaigns_login_path
    end
  end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
  def campaign_navigations
    [
      { text: t("campaigns.navigations.add_merchant"), icon: "plus", url: new_campaigns_merchant_path,
        active: active_class("merchants", "new") || active_class("merchants", "create") },
      { text: t("campaigns.navigations.account"), icon: "user", url: campaigns_account_path,
        active: active_class("marketers", "edit") || active_class("marketers", "update") },
      { text: t("campaigns.navigations.merchants"), icon: "building", url: campaigns_merchants_path,
      active: active_class("merchants", "index") }
    ]
  end
end

app/views/campaigns/invitations/_new_form.html.erb
<%= form_with model: marketer, url: campaigns_invitations_path, id: dom_id(marketer) do |form| %>
  <div class="form-group">
    <%= form.label :email, t('.email.label'), class: "form-label" %>

    <%= form.email_field :email,
          placeholder: t('.email.placeholder'), autocomplete: false, required: true, autofocus: true,
          class: "form-control #{'is-invalid' if marketer.errors.messages[:email].present?}" %>
    <% if marketer.errors.messages[:email].present? %>
      <div class="invalid-feedback">
        <% marketer.errors.messages[:email].each do |message| %>
          <span><%= message %></span>
        <% end %>
      </div>
    <% end %>
  </div>

  <%= form.submit t(".submit"), class: "mb-6 btn btn-primary" %>
<% end %>

app/views/campaigns/invitations/_update_form.html.erb
<%= form_with model: marketer, url: campaigns_invitation_path(token: params[:token]), id: dom_id(marketer) do |form| %>

  <div class="form-group">
    <%= form.label :email, t('.email.label'), class: "form-label" %>

    <%= form.email_field :email, disabled: true, 
          placeholder: t('.email.placeholder'), autocomplete: false, required: true,
          class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :full_name, t('.full_name.label'), class: "form-label" %>

    <%= form.text_field :full_name, autofocus: true, 
          placeholder: t('.full_name.placeholder'), autocomplete: false, required: true,
          class: "form-control #{'is-invalid' if marketer.errors[:full_name].present?}" %>

    <% if marketer.errors.messages[:full_name].present? %>
      <div class="invalid-feedback">
        <% marketer.errors.messages[:full_name].each do |message| %>
          <span><%= message %></span>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :password, t('.password.label'), class: "form-label" %>

    <%= form.password_field :password, required: true, autocomplete: false, autofocus: false,
        label: t('.password.label'), placeholder: t('.password.placeholder'),
        class: "form-control #{'is-invalid' if marketer.errors[:password].present?}"%>
    
    <% if marketer.errors.messages[:password].present? %>
      <div class="invalid-feedback">
        <% marketer.errors.messages[:password].each do |message| %>
          <span><%= message %></span>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :password_confirmation, t('.password_confirmation.label'), class: "form-label" %>

    <%= form.password_field :password_confirmation, required: true, autocomplete: false,
        label: t('.password_confirmation.label'), placeholder: t('.password_confirmation.placeholder'),
        class: "form-control #{'is-invalid' if marketer.errors[:password_confirmation].present?}" %>
    
    <% if marketer.errors.messages[:password_confirmation].present? %>
      <div class="invalid-feedback">
        <% marketer.errors.messages[:password_confirmation].each do |message| %>
          <span><%= message %></span>
        <% end %>
      </div>
    <% end %>
  </div>

  <%= form.submit t(".submit"), class: "mb-6 btn btn-primary" %>
<% end %>

app/views/campaigns/invitations/edit.html.erb
<div class="flex w-full flex-col justify-center mt-6 sm:max-w-[480px] mx-auto">
  <h3 class="text-xl text-center font-semi-bold tracking-tight text-gray-900 pb-4 truncate">
    <%= t('.title') %>
  </h3>

  <%= render 'campaigns/invitations/update_form', marketer: @marketer %>
</div>

app/views/campaigns/invitations/new.html.erb
<div class="px-2">
  <h3 class="text-xl text-center font-semi-bold tracking-tight text-gray-900 pb-4 truncate">
    <%= t('.title') %>
  </h3>

  <%= render 'campaigns/invitations/new_form', marketer: @marketer %>
</div>