config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Admin
  get "/admin", to: "admin/home#index"
  namespace :admin do
    resources :enterprises, except: %i[index destroy]
  end

  # Campaigns
  namespace :campaigns do
    get "marketer/show"
    # Invitations
    resources :invitations, param: :token, except: %i[index destroy]
    # Sessions
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    # Registration
    get "/account", to: "marketers#edit"
    patch "/account", to: "marketers#update"
    # Password
    resources :passwords, param: :token, except: %i[index show]

    # Enterprises
    resources :merchants, except: :destroy do
    end
    put "merchants/:id/location", to: "merchants#location", as: "merchant_location"

    get "/account", to: "marketers#edit"
    patch "/account", to: "marketers#update"
  end

  # Registration
  get "/account", to: "admins#edit"
  patch "/account", to: "admins#update"
  resources :user_invitations, only: %i[new create edit update]

  # Session
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  # Enterprises
  get "/settings", to: "enterprises#edit", as: :enterprise_setting
  delete "remove_user/:user_id", to: "enterprises#remove_user", as: :remove_enterprise_user

  # Branches
  resources :branches, except: %i[index destroy]

  # Password
  resources :passwords, param: :token, except: %i[index show]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :deliveries do
    collection do
      get :search_customer
      get :search_branch
    end
  end
  put "deliveries/:id/confirm_arrival", to: "deliveries#confirm_arrival", as: :confirm_arrival
  put "deliveries/:id/confirm_delivery", to: "deliveries#confirm_delivery", as: :confirm_delivery

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "enterprises#index"
end

app/controllers/admin/home_controller.rb
module Admin
  class HomeController < ApplicationController
    def index
      @enterprises = Enterprise.not_special.order(:created_at)
      @marketers = Marketer.order(:created_at)
    end
  end
end

app/views/admin/home/_enterprises.html.erb
<div class="w-full flex items-center pt-2 pb-3">
  <h4 class="text-xl/3 font-bold tracking-tight text-gray-900">
    <%= t('.title') %>
  </h4>

  <button class="btn btn-secondary ml-auto flex gap-2" type="button" data-controller="modal-trigger" 
      data-target="#manage-enterprise-modal" data-url="<%= new_admin_enterprise_path %>"
      data-action="modal-trigger#fireModalEvent">
    <%= render "shared/svgs/plus" %>
    <%= t(".add") %>
  </button>
</div>

<div class="bg-tp-soft-gray grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 rounded w-full p-2">
  <%= render partial: "admin/enterprises/enterprise", collection: enterprises, as: :enterprise %>
</div>

<%= render "shared/modal", id: "manage-enterprise-modal" %>

app/views/admin/home/_marketers.html.erb
<div class="w-full flex items-center pt-2 pb-3">
  <h4 class="text-xl/3 font-bold tracking-tight text-gray-900">
    <%= t('.title') %>
  </h4>

  <button class="btn btn-secondary ml-auto flex gap-2" type="button" data-controller="modal-trigger" 
      data-target="#invite-marketer-modal" data-url="<%= new_campaigns_invitation_path %>"
      data-action="modal-trigger#fireModalEvent">
    <%= render "shared/svgs/plus" %>
    <%= t(".invite") %>
  </button>
</div>

<div class="bg-tp-soft-gray grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 rounded w-full p-2">
  <%= render partial: "admin/marketers/marketer", collection: marketers, as: :marketer %>
</div>

<%= render "shared/modal", id: "invite-marketer-modal" %>

app/views/admin/home/index.html.erb
<div class="flex w-full flex-col justify-center w-full mx-auto px-2">
  <header>
    <h2 class="text-2xl/9 mt-6 font-bold tracking-tight text-gray-900">
      <%= t('.title') %>
    </h2>
  </header>

  <nav class="flex items-center gap-4 my-3">
    <%= link_to t('.enterprises'), admin_path(params: { option: "enterprises" }),
          class: "sub-nav-link #{active_nav_link('enterprises')}" %>
    <%= link_to t('.marketers'), admin_path(params: { option: "marketers" }),
          class: "sub-nav-link #{active_nav_link('marketers')}" %>
  </nav>
  
  <section>
    <% if params[:option] == "marketers" %>
      <%= render "admin/home/marketers", marketers: @marketers %>
    <% else %>
      <%= render "admin/home/enterprises", enterprises: @enterprises %>
    <% end %>
  </section>
</div>