config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Admin
  get "/admin", to: "admin/home#index"
  namespace :admin do
    resources :enterprises, except: %i[index destroy]
  end

  # Campaigns
  namespace :campaigns do
    get "marketer/show"
    # Invitations
    resources :invitations, param: :token, except: %i[index destroy]
    # Sessions
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    # Registration
    get "/account", to: "marketers#edit"
    patch "/account", to: "marketers#update"
    # Password
    resources :passwords, param: :token, except: %i[index show]

    # Enterprises
    resources :merchants, except: :destroy do
    end
    put "merchants/:id/location", to: "merchants#location", as: "merchant_location"

    get "/account", to: "marketers#edit"
    patch "/account", to: "marketers#update"
  end

  # Registration
  get "/account", to: "admins#edit"
  patch "/account", to: "admins#update"
  resources :user_invitations, only: %i[new create edit update]

  # Session
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  # Enterprises
  get "/settings", to: "enterprises#edit", as: :enterprise_setting
  delete "remove_user/:user_id", to: "enterprises#remove_user", as: :remove_enterprise_user

  # Branches
  resources :branches, except: %i[index destroy]

  # Password
  resources :passwords, param: :token, except: %i[index show]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :deliveries do
    collection do
      get :search_customer
      get :search_branch
    end
  end
  put "deliveries/:id/confirm_arrival", to: "deliveries#confirm_arrival", as: :confirm_arrival
  put "deliveries/:id/confirm_delivery", to: "deliveries#confirm_delivery", as: :confirm_delivery

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "enterprises#index"
end

app/controllers/admin/enterprises_controller.rb
module Admin
  class EnterprisesController < ApplicationController
    before_action :set_enterprise, only: %i[edit update]

    def create
      enterprise, manager = Enterprise.create_new(enterprise_params, manager_params)

      if enterprise.persisted?
        flash[:success] = I18n.t("flash.create_success", name: enterprise.escape_value(:name))
        redirect_to admin_path
      else
        render turbo_stream: turbo_stream.replace("new_enterprise", partial: "admin/enterprises/form",
                                                  locals: { enterprise:, manager: }),
                              status: :unprocessable_entity
      end
    end

    def new
      @enterprise = Enterprise.new(category: nil)
      @manager = @enterprise.managers.new

      respond_to do |format|
        format.json { render json: { html: render_to_string("admin/enterprises/new", layout: false, formats: :html) } }
      end
    end

    def edit
      respond_to do |format|
        format.json { render json: { html: render_to_string("admin/enterprises/edit", layout: false, formats: :html) } }
      end
    end

    def update
      if @enterprise.update(enterprise_params)
        flash[:success] = I18n.t("flash.update_success", name: @enterprise.escape_value(:name))
        redirect_to admin_path
      else
        render :edit, status: :unprocessable_entity
      end
    end

    private

    def enterprise_params
      params.require(:enterprise).permit(:name, :category, :description)
    end

    def manager_params
      params.require(:manager).permit(:telephone)
    end

    def set_enterprise
      @enterprise = Enterprise.find(params[:id])
    end
  end
end

app/controllers/enterprises_controller.rb
class EnterprisesController < ApplicationController
  allow_unauthenticated_access only: :index
  skip_before_action :set_enterprise, only: :index

  def index
    @enterprises = Enterprise.order(:created_at)
  end

  def edit
    @branches = Branch.order(:name)
    @users = Users::Admin.left_outer_joins([ :branch, :invited_by ])
                         .where(archived: false)
                         .select("users.*, branches.name AS branch_name,
                                  invited_bies_users.full_name AS invited_by_name")
                         .order(:created_at)
  end

  def remove_user
    authorize! :manage, @current_enterprise

    user = Users::Admin.find(params[:user_id])
    user.update_column(:archived, true)

    render turbo_stream: turbo_stream.remove(user)
  end
end

app/helpers/enterprises_helper.rb
module EnterprisesHelper
  def active_nav_link(option)
    return "active" if params[:option] == option
    return "active" if params[:option].nil? && option == "branches"
    return "active" if params[:option].nil? && option == "enterprises"

    ""
  end

  def enterprise_categories
    Enterprise.categories.except(:special).keys.map do |category|
      [ category, t("admin.enterprises.categories.#{category}") ]
    end
  end
end

app/views/admin/enterprises/_enterprise.html.erb
<div class="flex items-center rounded w-full h-16" id="<%= dom_id(enterprise) %>">
  <button class="btn btn-primary h-12 mx-auto w-full flex items-center justify-center text-base"
      type="button" data-controller="modal-trigger" 
      data-target="#manage-enterprise-modal" data-url="<%= edit_admin_enterprise_path(enterprise) %>"
      data-action="modal-trigger#fireModalEvent">
    <%= enterprise.name %>
  </button>
</div>

app/views/admin/enterprises/_form.html.erb
<% url = enterprise.persisted? ? admin_enterprise_path(enterprise) : admin_enterprises_path %>

<%= form_with model: enterprise, url:, id: dom_id(enterprise) do |form| %>
  <div class="form-group">
    <%= form.label :name, t('.name.label'), class: "form-label" %>
    <%= form.text_field :name, required: true, autofocus: true,
          autocomplete: "name", placeholder: t('.name.placeholder'),
          class: "form-control #{'is-invalid' if enterprise.errors.messages[:name].present?}" %>
    <% if enterprise.errors.messages[:name].present? %>
      <div class="invalid-feedback">
        <% enterprise.errors.messages[:name].each do |message| %>
          <span><%= message %></span>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :category, t('.category.label'), class: "form-label" %>
    
    <%= form.collection_select :category, enterprise_categories, :first, :last,
          { include_blank: t('.category.placeholder'), selected: enterprise.category },
          { class: "form-control #{'is-invalid' if enterprise.errors[:category].present?}", disabled: enterprise.persisted? } %>

    <% if enterprise.errors.messages[:category].present? %>
      <div class="invalid-feedback">
        <% enterprise.errors.messages[:category].each do |message| %>
          <span><%= message %></span>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :description, t('.description.label'), class: "form-label" %>
    <%= form.textarea :description, required: false, placeholder: t('.description.placeholder'),
          class: "form-control" %>
  </div>

  <% unless enterprise.persisted? %>
    <%= form.fields_for manager do |manager_form| %>
      <div class="flex justify-between items-center">
        <h4 class="mb-2"><%= t(".manager") %></h4>
      </div>

      <div class="form-group">
        <%= form.label :telephone, t('.telephone.label'), class: "form-label" %>
        <%= manager_form.text_field :telephone, placeholder: t('.telephone.placeholder'), name: "manager[telephone]",
              class: "form-control #{'is-invalid' if manager.errors.messages[:telephone].present?}",
              data: { "select-dropdown-target": "input", controller: "format-decimals", action: "format-decimals#formatValue" } %>

        <% if manager.errors.messages[:telephone].present? %>
          <div class="invalid-feedback">
            <% manager.errors.messages[:telephone].each do |message| %>
              <span><%= message %></span>
            <% end %>
          </div>  
        <% end %>  
      </div>
    <% end %>
  <% end %>
  

  <%= form.submit t(".submit.#{enterprise.persisted? ? 'update' : 'create'}"), class: "btn btn-primary mb-5" %>
<% end %>

app/views/admin/enterprises/edit.html.erb
<div class="w-full pt-2 px-4 max-w-[480px] m-auto">
  <h2 class="text-center text-2xl/9 font-semibold tracking-tight text-gray-900">
    <%= t('.title') %>
  </h2>

  <%= render "admin/enterprises/form", enterprise: @enterprise %>
</div>

app/views/admin/enterprises/new.html.erb
<div class="w-full pt-2 px-4 max-w-[480px] m-auto">
  <h2 class="text-center text-2xl/9 font-semibold tracking-tight text-gray-900">
    <%= t('.title') %>
  </h2>

  <%= render "admin/enterprises/form", enterprise: @enterprise, manager: @manager %>
</div>